### ISSUE TITLE
add in Proxy Support

### ISSUE THREAD

**Issue by bryancolligan** [dharmafly/noodle#100]
on line 120 of noodle.js add the following for proxy support:

  if (query.proxy) {
    requestOptions.proxy = query.proxy;
  }

**Comment by mikeatlas** [comment]
This breaks if ` noodle.fetch(url)` doesn't specify a query (but the documentation shows examples that this could be done). 

The workaround is to simply supply a `query` with every `noodle.fetch` call, but that's not so great.

I'll submit a PR fix for this, it should have checked if the query was passed first: 

```javascript
if (query && query.proxy) {
requestOptions.proxy = query.proxy;
}
```

**Comment by AaronAcerboni** [comment]
Thank you @mikeatlas

**Comment by mikeatlas** [comment]
Ah, I'm about to submit my own PR for something else, might as well while I'm in the code fix the other thing that was bothering me :+1:
