### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by OKNoah** [dharmafly/noodle#105]
Here is what happens after `npm install noodles --save`

	npm WARN package.json node@0.0.0 No description
	npm WARN package.json node@0.0.0 No repository field.
	npm WARN package.json node@0.0.0 No README data
	npm WARN package.json gently@0.9.1 No repository field.
	^C
	My-User-Names-Air:slipstream My-User-Name$ npm install noodlejs --save
	npm WARN package.json node@0.0.0 No description
	npm WARN package.json node@0.0.0 No repository field.
	npm WARN package.json node@0.0.0 No README data
	npm WARN engine noodlejs@0.3.1: wanted: {"node":"0.6.x"} (current: {"node":"0.11.14","npm":"2.0.0"})
	/
	> node-expat@2.0.0 install /Users/My-User-Name/Documents/dev/slipstream/node_modules/noodlejs/node_modules/xml2json/node_modules/node-expat
	> node-gyp rebuild

	child_process: customFds option is deprecated, use stdio instead.
	  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
	  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
	../deps/libexpat/lib/xmltok.c:471:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
	};
	^
	../deps/libexpat/lib/xmltok.c:484:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
	};
	^
	../deps/libexpat/lib/xmltok.c:504:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
	};
	^
	../deps/libexpat/lib/xmltok.c:517:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
	};
	^
	../deps/libexpat/lib/xmltok.c:730:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
	};
	^
	../deps/libexpat/lib/xmltok.c:749:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
	};
	^
	../deps/libexpat/lib/xmltok.c:762:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
	};
	^
	../deps/libexpat/lib/xmltok.c:775:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
	};
	^
	../deps/libexpat/lib/xmltok.c:871:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
	};
	^
	../deps/libexpat/lib/xmltok.c:890:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
	};
	^
	10 warnings generated.
	  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
	  LIBTOOL-STATIC Release/libexpat.a
	  CXX(target) Release/obj.target/node_expat/node-expat.o
	../node-expat.cc:54:34: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
	  static Handle<Value> New(const Arguments& args)
												^~~~~~~~~
												v8::internal::Arguments
	/Users/My-User-Name/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
	class Arguments;
			^
	../node-expat.cc:99:36: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
	  static Handle<Value> Parse(const Arguments& args)
												  ^~~~~~~~~
												  v8::internal::Arguments
	/Users/My-User-Name/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
	class Arguments;
			^
	../node-expat.cc:171:42: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
	  static Handle<Value> SetEncoding(const Arguments& args)
														  ^~~~~~~~~
														  v8::internal::Arguments
	/Users/My-User-Name/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
	class Arguments;
			^
	../node-expat.cc:198:39: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
	  static Handle<Value> GetError(const Arguments& args)
													  ^~~~~~~~~
													  v8::internal::Arguments
	/Users/My-User-Name/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
	class Arguments;
			^
	../node-expat.cc:212:35: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
	  static Handle<Value> Stop(const Arguments& args)
												 ^~~~~~~~~
												 v8::internal::Arguments
	/Users/My-User-Name/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
	class Arguments;
			^
	../node-expat.cc:229:37: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
	  static Handle<Value> Resume(const Arguments& args)
													^~~~~~~~~
													v8::internal::Arguments
	/Users/My-User-Name/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
	class Arguments;
			^
	../node-expat.cc:244:36: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
	  static Handle<Value> Reset(const Arguments& args)
												  ^~~~~~~~~
												  v8::internal::Arguments
	/Users/My-User-Name/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
	class Arguments;
			^
	../node-expat.cc:272:51: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
	  static Handle<Value> GetCurrentLineNumber(const Arguments& args)
																	  ^~~~~~~~~
																	  v8::internal::Arguments
	/Users/My-User-Name/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
	class Arguments;
			^
	../node-expat.cc:285:53: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
	  static Handle<Value> GetCurrentColumnNumber(const Arguments& args)
																		 ^~~~~~~~~
																		 v8::internal::Arguments
	/Users/My-User-Name/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
	class Arguments;
			^
	../node-expat.cc:298:50: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
	  static Handle<Value> GetCurrentByteIndex(const Arguments& args)
																	 ^~~~~~~~~
																	 v8::internal::Arguments
	/Users/My-User-Name/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
	class Arguments;
			^
	../node-expat.cc:22:17: error: calling a protected constructor of class 'v8::HandleScope'
		 HandleScope scope;
						 ^
	/Users/My-User-Name/.node-gyp/0.11.14/deps/v8/include/v8.h:816:13: note: declared protected here
	  V8_INLINE HandleScope() {}
					^
	../node-expat.cc:23:55: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'Handle<v8::Value> (const v8::internal::Arguments &)'
		 Local<FunctionTemplate> t = FunctionTemplate::New(New);
																			^~~
	/Users/My-User-Name/.node-gyp/0.11.14/deps/v8/include/v8.h:3435:16: note: passing argument to parameter 'isolate' here
			Isolate* isolate,
						^
	../node-expat.cc:27:43: error: cannot initialize a parameter of type 'v8::FunctionCallback' (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') with an lvalue of type
			'Handle<v8::Value> (const v8::internal::Arguments &)': type mismatch at 1st parameter ('const FunctionCallbackInfo<v8::Value> &' vs 'const v8::internal::Arguments &')
		 NODE_SET_PROTOTYPE_METHOD(t, "parse", Parse);
															^~~~~
	/Users/My-User-Name/.node-gyp/0.11.14/src/node.h:229:60: note: passing argument to parameter 'callback' here
													  v8::FunctionCallback callback) {
																				  ^
	../node-expat.cc:28:49: error: cannot initialize a parameter of type 'v8::FunctionCallback' (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') with an lvalue of type
			'Handle<v8::Value> (const v8::internal::Arguments &)': type mismatch at 1st parameter ('const FunctionCallbackInfo<v8::Value> &' vs 'const v8::internal::Arguments &')
		 NODE_SET_PROTOTYPE_METHOD(t, "setEncoding", SetEncoding);
																	^~~~~~~~~~~
	/Users/My-User-Name/.node-gyp/0.11.14/src/node.h:229:60: note: passing argument to parameter 'callback' here
													  v8::FunctionCallback callback) {
																				  ^
	../node-expat.cc:29:46: error: cannot initialize a parameter of type 'v8::FunctionCallback' (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') with an lvalue of type
			'Handle<v8::Value> (const v8::internal::Arguments &)': type mismatch at 1st parameter ('const FunctionCallbackInfo<v8::Value> &' vs 'const v8::internal::Arguments &')
		 NODE_SET_PROTOTYPE_METHOD(t, "getError", GetError);
																^~~~~~~~
	/Users/My-User-Name/.node-gyp/0.11.14/src/node.h:229:60: note: passing argument to parameter 'callback' here
													  v8::FunctionCallback callback) {
																				  ^
	../node-expat.cc:30:42: error: cannot initialize a parameter of type 'v8::FunctionCallback' (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') with an lvalue of type
			'Handle<v8::Value> (const v8::internal::Arguments &)': type mismatch at 1st parameter ('const FunctionCallbackInfo<v8::Value> &' vs 'const v8::internal::Arguments &')
		 NODE_SET_PROTOTYPE_METHOD(t, "stop", Stop);
														  ^~~~
	/Users/My-User-Name/.node-gyp/0.11.14/src/node.h:229:60: note: passing argument to parameter 'callback' here
													  v8::FunctionCallback callback) {
																				  ^
	../node-expat.cc:31:44: error: cannot initialize a parameter of type 'v8::FunctionCallback' (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') with an lvalue of type
			'Handle<v8::Value> (const v8::internal::Arguments &)': type mismatch at 1st parameter ('const FunctionCallbackInfo<v8::Value> &' vs 'const v8::internal::Arguments &')
		 NODE_SET_PROTOTYPE_METHOD(t, "resume", Resume);
															 ^~~~~~
	/Users/My-User-Name/.node-gyp/0.11.14/src/node.h:229:60: note: passing argument to parameter 'callback' here
													  v8::FunctionCallback callback) {
																				  ^
	../node-expat.cc:32:43: error: cannot initialize a parameter of type 'v8::FunctionCallback' (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') with an lvalue of type
			'Handle<v8::Value> (const v8::internal::Arguments &)': type mismatch at 1st parameter ('const FunctionCallbackInfo<v8::Value> &' vs 'const v8::internal::Arguments &')
		 NODE_SET_PROTOTYPE_METHOD(t, "reset", Reset);
															^~~~~
	/Users/My-User-Name/.node-gyp/0.11.14/src/node.h:229:60: note: passing argument to parameter 'callback' here
													  v8::FunctionCallback callback) {
																				  ^
	../node-expat.cc:33:58: error: cannot initialize a parameter of type 'v8::FunctionCallback' (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') with an lvalue of type
			'Handle<v8::Value> (const v8::internal::Arguments &)': type mismatch at 1st parameter ('const FunctionCallbackInfo<v8::Value> &' vs 'const v8::internal::Arguments &')
		 NODE_SET_PROTOTYPE_METHOD(t, "getCurrentLineNumber", GetCurrentLineNumber);
																				^~~~~~~~~~~~~~~~~~~~
	/Users/My-User-Name/.node-gyp/0.11.14/src/node.h:229:60: note: passing argument to parameter 'callback' here
													  v8::FunctionCallback callback) {
																				  ^
	fatal error: too many errors emitted, stopping now [-ferror-limit=]
	20 errors generated.
	make: *** [Release/obj.target/node_expat/node-expat.o] Error 1
	gyp ERR! build error
	gyp ERR! stack Error: `make` failed with exit code: 2
	gyp ERR! stack     at ChildProcess.onExit (/Users/My-User-Name/.nvm/v0.11.14/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
	gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1059:12)
	gyp ERR! System Darwin 14.0.0
	gyp ERR! command "node" "/Users/My-User-Name/.nvm/v0.11.14/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
	gyp ERR! cwd /Users/My-User-Name/Documents/dev/slipstream/node_modules/noodlejs/node_modules/xml2json/node_modules/node-expat
	gyp ERR! node -v v0.11.14
	gyp ERR! node-gyp -v v1.0.2
	gyp ERR! not ok

	npm ERR! Darwin 14.0.0
	npm ERR! argv "/Users/My-User-Name/.nvm/v0.11.14/bin/node" "/Users/My-User-Name/.nvm/v0.11.14/bin/npm" "install" "noodlejs" "--save"
	npm ERR! node v0.11.14
	npm ERR! npm  v2.0.0
	npm ERR! code ELIFECYCLE
	npm ERR! node-expat@2.0.0 install: `node-gyp rebuild`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the node-expat@2.0.0 install script.
	npm ERR! This is most likely a problem with the node-expat package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node-gyp rebuild
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls node-expat
	npm ERR! There is likely additional logging output above.

**Comment by OKNoah** [comment]
Switching to `0.10.33` fixes this, but with errors. Something to watch out for next version.

**Comment by freder** [comment]
changing the [`xml2json` version that `noodle` depends on](https://github.com/dharmafly/noodle/blob/master/package.json#L18) to `^0.5.1` helped for me. — I think the dependencies for this package should be updated.

**Comment by premasagar** [comment]
Thanks for pointing this out. Noodle hasn't been updated for a while.
If you have your package.json all updated, feel free to send a pull request.

**Comment by freder** [comment]
created a pull request: https://github.com/dharmafly/noodle/pull/109

**Comment by premasagar** [comment]
Thanks @freder

**Comment by at0mat** [comment]
I'm still experiencing exactly this issue for 'npm install --save noodlejs' . Is a patch version bump required?

**Comment by premasagar** [comment]
I haven't yet upped the NPM version. I will do so shortly. Until then,
please use the source code in the repo.


-- 
*Prem Rose*
premasagar.com

**Comment by premasagar** [comment]
I've pushed an updated version to NPM.
