### ISSUE TITLE
Selecting by text for hierarchical/nested data

### ISSUE THREAD

**Issue by tomchambers2** [dharmafly/noodle#107]
I'm not sure whether this is possible with noodlejs from my reading of the reference. I am trying to read film data from a page like this: http://www.britinfo.net/cinema/cinema-listings-1003671.htm

```
query = {
    url: 'http://www.britinfo.net/cinema/cinema-listings-1003671.htm',
    type: 'html',
    selector: 'a b',
    extract: 'text'
  }

alert: [ "A Most Violent Year", "American Sniper", "Birdman", "Ex Machina", "Foxcatcher", "Into the Woods", "Kingsman: The Secret Service", "Testament of Youth", "The Imitation Game", "The Theory of Everything", "Whiplash", "Wild" ]
```

I then need to make another query to get the dates in `small` tags but only when nested within/adjacent to `<a><b>A most violent year</b></a>. Then get the times adjacent to `Wednesday 28th January`

**Comment by premasagar** [comment]
Hi @tomchambers2. The titles and the dates in such are case are related by their closest parent, in this case, the `td.tdtext1` element. I would grab the individual films in those elements as html, and then process the rest of the data in the client:

```js
{
    url: 'http://www.britinfo.net/cinema/cinema-listings-1003671.htm',
    type: 'html',
    selector: 'td.tdtext1',
    extract: 'html'
  }
```
